apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns-deployment
  labels:
    app: coredns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      containers:
      - name: coredns
        image: coredns/coredns
        command: ["/coredns", "-conf", "/etc/coredns/Corefile"]
        ports:
        - containerPort: 53
        volumeMounts:
        - name: corefile-config
          mountPath: /etc/coredns
        - name: zone-config
          mountPath: /etc/coredns/zone
      volumes:
      - name: corefile-config
        configMap:
          name: corefile
      - name: zone-config
        projected:
          sources:
          - configMap:
              name: local.zone
         #- configMap:
         #    name: xxxxx.zone
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.137.101
  ports:
    - name: coredns-port
      port: 53
      protocol: UDP
  selector:
    app: coredns
